Version: 1
Include:
  - ./FmuImporterIncludeConfig.yaml

Parameters:
    #Overrides external include parameter
  - VariableName: Float64_fixed_parameter
    Value: 7.0
    # Test override for string parameter
  - VariableName: String_parameter
    Value: "Local Data"
    # Test override for binary parameter
  - VariableName: Binary_input
    Value: 626172

IgnoreUnmappedVariables: False
StepSize: 200000

VariableMappings:
  - VariableName: Float64_tunable_parameter
    TopicName: Float64_tunable_parameter_To_Int32
    Transformation:
      Offset: 1.0
      Factor: 2.0
      TransmissionType: Int32
  - VariableName: Float64_continuous_output
    Transformation:
      Offset: 1
      Factor: 2
