Version: 1

Include:
  - ./FmuImporterConfig.yaml

ParameterSet:
  Description: Externally included ParamSet
  Parameters:
    - VarName: Float64_fixed_parameter
      Description: 
      Value: 42
    - VarName: Float64_tunable_parameter
      Description: 
      Value: 42
