ParameterSet:
  IncludeParameterSets:
    - ./FmuImporterIncludeConfig.yaml
  Parameters:
    - VarName: Float64_fixed_parameter
      Description: Overrides external include parameter
      Value: 7.0
    - VarName: String_parameter
      Description: Test override for string parameter
      Value: "Local Data"
    - VarName: Binary_input
      Description: Test override for binary parameter
      Value: "626172"

Connectors:
  - VariableName: UInt16_input
    TopicName: UInt16_To_Double
    Transformation:
      Offset: -2.0
      Factor: 2.0
      Type: Float64
