ParameterSets:
  - Name: IncludeParamSet
    Description: Locally included parameter set
    Parameters:
      - VarName: Float64_fixed_parameter
        Description: Overrides external include parameter
        Value: 7.0
      - VarName: String_parameter
        Value: "Local include data"
  - Name: DefaultParamSet
    IncludeParameterSets:
      - RefName: IncludeParamSet
        FilePath: ./FmuImporterIncludeConfig.yaml
      - RefName: IncludeParamSet
    Parameters:
      - VarName: UInt16_input
        Description: Feedthrough UInt16
        Value: 42
      - VarName: String_parameter
        Value: "LocalData"
      - VarName: Binary_input
        Value: "626172"