name: Build the SIL Kit FMU Importer (.NET 6)

# Define the triggers for this workflow
on:
  workflow_dispatch:
  pull_request:
  push:
    #branches:
    #  - 'main'

jobs:
  build-windows:

    runs-on: windows

    steps:

    # Check out this Git repo
    - uses: actions/checkout@v3

    - name: Build & Publish
      run: dotnet build ./FmuImporter/BuildAll/Build.csproj -v:m

  build-linux:

    runs-on: [Linux]
    steps:
    # Check out this Git repo
    - uses: actions/checkout@v3
    - name: Build & Publish
      run: dotnet build ./FmuImporter/BuildAll/Build.csproj -v:m
