name: Build the SIL Kit FMU Importer (.NET 6)

# Define the triggers for this workflow
on:
  workflow_dispatch:
  pull_request:
  push:
    #branches:
    #  - 'main'

jobs:
  build-windows:

    runs-on: windows

    steps:

    # Check out this Git repo
    - uses: actions/checkout@v3

    - name: Build
      run: dotnet build ./FmuImporter/FmuImporter/FmuImporter.csproj -c Debug --no-self-contained -r win-x64

  build-linux:

    runs-on: [Linux]
    steps:
    # Check out this Git repo
    - uses: actions/checkout@v3
    - name: build step
      run: dotnet build ./FmuImporter/FmuImporter/FmuImporter.csproj -c Debug --no-self-contained -r linux-x64
